# Generated by Django 5.0.3 on 2024-03-21 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EchoPenApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=10000)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('REJ', 'Rejected'), ('PUB', 'Published')], default='PEN', max_length=3)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('like', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
